kind: Service
apiVersion: v1
metadata:
  name: oauth-pwd-service
spec:
  type: NodePort
  selector:
    app: oauth-pwd
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 32083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-pwd-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth-pwd
    spec:
      containers:
        - name: oauth-pwd-controller
          image: oauth-pwd:1.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: msyql520
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 10
