spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #自动创建表
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

server:
  port: 8083

auth2:
  enabled: true
  certPath: /Users/zhuhuiyuan/Downloads
  clientId: cmb_kg
  clientSecret: ruyiruyi