spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: mysql520
  jpa:
    hibernate:
      ddl-auto: update #自动创建表
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

server:
  port: 8083

client-config:
  enabled: true
  clientId: client-pwd
  clientSecret: mypass
  authorizedGrantTypes: password,refresh_token
  resourceIds: auth-server
  scope: read,write
  accessTokenValidity: 3600
  refreshTokenValidity: 36000
  scopeRequire: true
  secretRequire: true

#
#  Client client = new Client();
#  client.setClientId(clientId);
#  client.setAuthorizedGrantTypes("password,refresh_token");
#  client.setAccessTokenValidity(3600 * 10);
#  client.setClientSecret("{bcrypt}$2a$10$COmo8Sf6R1f4R6Yilhf5ruOEzyNLY.XDr3Ga55zbAjaennLKkAl88");
#  client.setRefreshTokenValidity(3600 * 20);
#  client.setResourceIds("auth-resource");
#  client.setScope("read,write");
#  client.setScopeRequire(true);
#  client.setSecretRequire(true);
